---
- name: Trend
  brand: 'Safety 1st'
  category: 'carrinho'
  image_url: https://www.safety1st.com.br/imagens/medium/medium_D968B_carrinho_trend_safety-1st_red_perspectiva_esquerda_padrao_IMG_8947.jpg?1519151885
  for: Para crianças de 0 meses a 15 kg
  desc1: Carrinho com fechamento guarda-chuva compatível com bebê conforto, assento reversível e removível, com encosto reclinável em 3 posições.
  desc2:
    <p>Carrinho com fechamento guarda-chuva compatível com bebê conforto, assento reversível e removível, com encosto reclinável em 3 posições.</p>
    <p>O Carrinho Trend Safety 1st possui 3 posições do encosto sendo a primeira sentado, a segunda levemente reclinado e a terceira deitado. O assento pode ser revertido, de frente para os pais ou virado para o mundo, e pode ser removido para armazenar ou encaixar o bebê conforto (vendido separadamente com base veicular).</p>
    <p>Fechamento exclusivo na categoria Travel System tipo guarda-chuva, compacto e leve. Possui 4 rodas duplas com trava de direcionamento nas rodas dianteiras e freios interligados nas rodas traseiras, manopla dupla acolchoada, amplo cesto de compras para até 4,5kg com zíper lateral que facilita o acesso.</p>
    <p>Capota retrátil e extensível com para-sol e visor para os pais, cinto de 5 pontos com protetor de ombro acolchoado, 3 alturas para cinto e apoio para os pés emborrachado. Tecido fácil de limpar. Para proceder com o fechamento correto do carrinho, o assento deve estar revertido contrário a visão de quem guia.</p>
  specs:
    - name: "NCM"
      desc: "94.018.000"
    - name: "Nome do carrinho"
      desc: "Trend"
    - name: "NORMA ABNT NBR 14389"
      desc: "INOR.E.C-CPC.00338/17"
    - name: "Peso recomendado"
      desc: "0 a 15kg"
    - name: "Fechamento"
      desc: "Envelope"
    - name: "Reclinável"
      desc: "3 posições"
    - name: "Apoio para os pés"
      desc: "Sim"
    - name: "Assento/Alça reversível"
      desc: "Assento reversível"
    - name: "Capota"
      desc: "Retrátil, com visor e removível"
    - name: "Manopla"
      desc: "Única e ajustável em altura"
    - name: "Barra frontal"
      name: "Sim"
    - name: "Bandeja"
      desc: "Não"
    - name: "Cinto de segurança"
      desc: "5 pontos com ajuste de altura"
    - name: "Cesto"
      desc: "Capacidade 3kg"
    - name: "Rodas"
      desc: "4 rodas"
    - name: "Freios"
      desc: "sim"
    - name: "Trava de direcionamento"
      desc: "Rodas dianteiras"
    - name: "Material/Composição"
      desc: "Alumínio, Polipropileno, Polietileno e Poliéster."
    - name: "Peso do Produto"
      desc: "8,8kg"
    - name: "Dimensões do Produto (cm)"
      desc: "98,5 x 64,5 x 101,5 cm"
    - name: "Nome do bebê conforto"
      desc: "Bebê conforto Citi com Base"
    - name: "Norma ABNT NBR 14400"
      desc: "INOR E.C-DRC.013-10/09"
    - name: "Grupos"
      desc: "0+"
    - name: "Peso recomendado"
      desc: "0 a 13kg"
    - name: "Instalação"
      desc: "De costas para o movimento"
    - name: "Redutor de assento"
      desc: "Sim"
    - name: "Apoio de cabeça"
      desc: "Sim"
    - name: "Cinto de segurança"
      desc: "sim, com ajuste de altura"
    - name: "Material/Composição"
      desc: "Polipropileno e Poliéster"
    - name: "Acompanha base"
      desc: "Sim"
    - name: "Peso do Produto"
      desc: "3,1kg"
    - name: "Dimensões do Produto (cm)"
      desc: "38 x 41 x 55"

- name: Zippy
  brand: 'Safety 1st'
  category: 'carrinho'
  image_url: 'https://www.safety1st.com.br/imagens/big/big_D968B_carrinho_trend_safety-1st_red_perspectiva_esquerda_padrao_IMG_8947.jpg?1519151885'
  for: Para crianças de 7,2 meses a 15 kg
  desc1: Carrinho portátil com tamanho fechado super compacto de apenas 54,4 x 40 x 16 cm.
  desc2:
    <p>Carrinho portátil com tamanho fechado super compacto de apenas 54,4 x 40 x 16 cm.</p>
    <p>Leve estrutura de alumínio, pesando somente 5,4 kg, com bolsa para transporte para facilitar a vida dos pais. Mantém o conforto com as 2 posições de reclínio e capota com proteção UV50+.</p>
  specs:
    - name: "NCM"
      desc: "94.018.000"
    - name: "Nome do carrinho"
      desc: "Zippy"
    - name: "NORMA ABNT NBR 14389"
      desc: "INOR.E.C-CPC.00338/17"
    - name: "Peso recomendado"
      desc: "0 a 15kg"
    - name: "Fechamento"
      desc: "Envelope"
    - name: "Reclinável"
      desc: "3 posições"
    - name: "Apoio para os pés"
      desc: "Sim"
    - name: "Assento/Alça reversível"
      desc: "Assento reversível"
    - name: "Capota"
      desc: "Retrátil, com visor e removível"
    - name: "Manopla"
      desc: "Única e ajustável em altura"
    - name: "Barra frontal"
      name: "Sim"
    - name: "Bandeja"
      desc: "Não"
    - name: "Cinto de segurança"
      desc: "5 pontos com ajuste de altura"
    - name: "Cesto"
      desc: "Capacidade 3kg"
    - name: "Rodas"
      desc: "4 rodas"
    - name: "Freios"
      desc: "sim"
    - name: "Trava de direcionamento"
      desc: "Rodas dianteiras"
    - name: "Material/Composição"
      desc: "Alumínio, Polipropileno, Polietileno e Poliéster."
    - name: "Peso do Produto"
      desc: "8,8kg"
    - name: "Dimensões do Produto (cm)"
      desc: "98,5 x 64,5 x 101,5 cm"
    - name: "Nome do bebê conforto"
      desc: "Bebê conforto Citi com Base"
    - name: "Norma ABNT NBR 14400"
      desc: "INOR E.C-DRC.013-10/09"
    - name: "Grupos"
      desc: "0+"
    - name: "Peso recomendado"
      desc: "0 a 13kg"
    - name: "Instalação"
      desc: "De costas para o movimento"
    - name: "Redutor de assento"
      desc: "Sim"
    - name: "Apoio de cabeça"
      desc: "Sim"
    - name: "Cinto de segurança"
      desc: "sim, com ajuste de altura"
    - name: "Material/Composição"
      desc: "Polipropileno e Poliéster"
    - name: "Acompanha base"
      desc: "Sim"
    - name: "Peso do Produto"
      desc: "3,1kg"
    - name: "Dimensões do Produto (cm)"
      desc: "38 x 41 x 55"

- name: Andador Melody Garden
  brand: 'Safety 1st'
  category: 'Acessórios'
  image_url: https://www.safety1st.com.br/imagens/medium/medium_11389_activity_centre_melody_garden_safety_1st_lifestyle.jpg?1317837773
  for: Para crianças de 7,2 meses a 12 kg
  desc1: Centro de atividades completo, com funções de balanço e andador. Assento giratório 360º removível e lavável, bandeja removível com brinquedos, luzes e sons da natureza.
  desc2:
    <p>Centro de atividades completo, com funções de balanço e andador. Assento giratório 360º removível e lavável, bandeja removível com brinquedos, luzes e sons da natureza.</p>
    <p>Funções de balanço, andador e centro de entretenimento com 3 posições de altura e assento giratório 360º removível e lavável. Bandeja removível com brinquedos, luzes e sons da natureza.</p>
    <p>Possui exclusivo sistema anti-quedas que evita acidentes em escadas e pisos irregulares, aprovado pelo INMETRO conforme a norma ABNT NBR 16.311 para crianças entre cerca de 6 meses até 12kg.</p>
  specs:
    - name: "Tipo"
      desc: "Centro de Atividades"

- name: MiloFix
  brand: 'Maxi-Cosi'
  category: 'Cadeirinha'
  image_url: 'https://www.dorel.com.br/imagens/medium/medium_8536_cadeirinha_milo_fix_maxi_cosi_black_raven_frente.jpg?1447418999'
  for: Para crianças de 0 meses a 18 kg
  desc1: Cadeirinha do nascimento aos 18kg com fixação ISOFIX. É reversível e permanece até os 13kg de costas para o movimento, aumentando a segurança e o conforto dos bebês.
  desc2:
    <p>Cadeirinha do nascimento aos 18kg com fixação ISOFIX. É reversível e permanece até os 13kg de costas para o movimento, aumentando a segurança e o conforto dos bebês.</p>
    <p>Sistema de reclínio ideal para os recém-nascidos, 6 posições de ajuste do apoio de cabeça em conjunto com a altura dos cintos e assento acolchoado ultra macio lavável na máquina.</p>
    <p>Fixação ISOFIX super segura, com indicadores que mostram se a instalação está correta e ponto de ancoragem superior modelo Top Tether para maior estabilidade.</p>
    <p>Instalação de frente e de costas para o movimento ajustável com um simples giro da base e ganchos laterais para apoiar os cintos enquanto acomoda a criança.</p>
    <p>Aprovado pelo INMETRO conforme a norma ABNT NBR 14.400 para crianças do nascimento aos 18kg (Grupos 0+ e 1) e pelos mais rígidos testes internacionais de segurança.</p>
  specs:
    - name: "NCM"
      desc: "94.018.000"
    - name: "Tipo"
      desc: "Cadeira para Auto"
    - name: "NORMA ABNT NBR 14389"
      desc: "INOR.E.C-CPC.00338/17"
    - name: "Peso recomendado"
      desc: "0 a 15kg"
    - name: "Fechamento"
      desc: "Envelope"
    - name: "Reclinável"
      desc: "3 posições"
    - name: "Apoio para os pés"
      desc: "Sim"
    - name: "Assento/Alça reversível"
      desc: "Assento reversível"
    - name: "Capota"
      desc: "Retrátil, com visor e removível"
    - name: "Manopla"
      desc: "Única e ajustável em altura"
    - name: "Barra frontal"
      name: "Sim"
    - name: "Bandeja"
      desc: "Não"
    - name: "Cinto de segurança"
      desc: "5 pontos com ajuste de altura"
    - name: "Cesto"
      desc: "Capacidade 3kg"
    - name: "Rodas"
      desc: "4 rodas"
    - name: "Freios"
      desc: "sim"
    - name: "Trava de direcionamento"
      desc: "Rodas dianteiras"
    - name: "Material/Composição"
      desc: "Alumínio, Polipropileno, Polietileno e Poliéster."
    - name: "Peso do Produto"
      desc: "8,8kg"
    - name: "Dimensões do Produto (cm)"
      desc: "98,5 x 64,5 x 101,5 cm"
    - name: "Nome do bebê conforto"
      desc: "Bebê conforto Citi com Base"
    - name: "Norma ABNT NBR 14400"
      desc: "INOR E.C-DRC.013-10/09"
    - name: "Grupos"
      desc: "0+"
    - name: "Peso recomendado"
      desc: "0 a 13kg"
    - name: "Instalação"
      desc: "De costas para o movimento"
    - name: "Redutor de assento"
      desc: "Sim"
    - name: "Apoio de cabeça"
      desc: "Sim"
    - name: "Cinto de segurança"
      desc: "sim, com ajuste de altura"
    - name: "Material/Composição"
      desc: "Polipropileno e Poliéster"
    - name: "Acompanha base"
      desc: "Sim"
    - name: "Peso do Produto"
      desc: "3,1kg"
    - name: "Dimensões do Produto (cm)"
      desc: "38 x 41 x 55"